[OPTIONAL]ALTER TABLE TRANSACTIONDETAIL ADD COLUMN (PREDEFINEDRATE NUMBER);
[OPTIONAL]ALTER TABLE TRANSACTION ADD COLUMN (BILLINGDATE TIMESTAMP);
[OPTIONAL]ALTER TABLE PARTY ADD COLUMN (TRANSPORTER VARCHAR2(256));
[OPTIONAL]ALTER TABLE TRANSACTION ADD COLUMN (LABOURCHARGE NUMBER);

