--[OPTIONAL]
--ALTER TABLE TRANSACTIONDETAIL ADD COLUMN (PREDEFINEDRATE NUMBER);
--[OPTIONAL]
--ALTER TABLE TRANSACTION ADD COLUMN (BILLINGDATE TIMESTAMP);
ALTER TABLE TRANSACTION MODIFY COLUMN BILLINGDATE TIMESTAMP;